on:
  workflow_dispatch:

permissions: {}

concurrency:
  group: yolo
  cancel-in-progress: true

jobs:
  do-things:
    runs-on: ubuntu-latest
    name: do-things
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - run: |
          gh issue create --title "A new issue" --body "Here are more details."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

  